CUDA_VISIBLE_DEVICES=0 python sem_seg_main.py \
        --run branch \
        --obj_path data/scene0002_00/scene0002_00_vh_clean_2.ply \
        --output_dir results/demo/room/scene0002_00/focal_length/rand_focal_beach_house \
        --prompt "a beach house by the sea" \
        --label 2 \
        --sigma 5.0  \
        --clamp tanh \
        --n_normaugs 4 \
        --n_augs 1 \
        --normmincrop 0.1 \
        --normmaxcrop 0.1 \
        --geoloss \
        --colordepth 2 \
        --normdepth 2   \
        --frontview \
        --frontview_std 4 \
        --clipavg view \
        --lr_decay 0.9 \
        --clamp tanh \
        --normclamp tanh  \
        --maxcrop 1.0 \
        --save_render \
        --seed 11 \
        --n_iter 1000 \
        --learning_rate 0.0005 \
        --normal_learning_rate 0.0005 \
        --background 1 1 1 \
        --frontview_center 1.8707 0.6303 \
        --lighting \
        --normratio 0.05 \
        --color_only \
        --render_all_grad_one \
        --focus_one_thing \
        --rand_focal