python main.py \
--run branch \
--obj_path data/source_meshes/horse.obj \
--sigma 5.0 \
--geoloss \
--clamp tanh \
--n_normaugs 4 \
--n_augs 1 \
--normmincrop 0.1 \
--normmaxcrop 0.1 \
--colordepth 2 \
--normdepth 2 \
--frontview \
--frontview_std 4 \
--clipavg view \
--lr_decay 0.9 \
--clamp tanh \
--normclamp tanh \
--maxcrop 1.0 \
--save_render \
--seed 48240889 \
--save_render \
--n_iter 1500 \
--frontview_center 5.4 0.4 \
--background 0.5 0.5 0.5 \
--prompt an image of a horse with armour \
--output_dir results/demo/horse/zebra_and_armour \
--rand_background