title: Text2Mesh: Text-Driven Neural Stylization for Meshes.
description: Oscar Michel*<sup>1</sup>, Roi Bar-On*<sup>1,2</sup>, Richard Liu*<sup>1</sup>, Sagie Benaim<sup>2</sup>, Rana Hanocka<sup>1</sup>
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0

paper:
  url: arxiv.com
  supp_url: arxiv.com/supp
  affiliations: <sup>1</sup>University Of Chicago, &nbsp; <sup>2</sup>Tel Aviv University
